import {useEffect, useState} from 'react'
import Navbar from "../../components/Navbar";
import Head from "next/head";
import BillingDetails from "../../components/BillingDetails";
import AccountNavigation from "../../components/AccountNavigation";
import {supabaseClient} from "../../supabase";
import {InformationCircleIcon} from "@heroicons/react/outline";

export default function AccountPage() {
    const [entitlement, setEntitlement] = useState(false);

    const getEntitlement = async() => {
        const entitlementResponse = await supabaseClient.rpc('get_entitlements', {
            _user_id: supabaseClient.auth.user().id
        });

        if(!entitlementResponse?.data?.[0]) {
            return;
        }

        setEntitlement(entitlementResponse.data[0]);
    }

    useEffect(() => {
        getEntitlement();
    }, []);

    return (
        <>
            <Head>
                <title>Skopdoc: Gerencie sua conta</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className="h-full bg-gray-100">
                <Navbar/>
                <main className="max-w-7xl mx-auto pb-10 lg:py-12 lg:px-8">
                    <div className="lg:grid lg:grid-cols-12 lg:gap-x-5">
                        <AccountNavigation current="/account/subscription"/>

                        {/* Payment details */}
                        <div className="space-y-6 sm:px-6 lg:px-0 lg:col-span-9">
                            <BillingDetails/>

                            {/* Plan */}
                            <section aria-labelledby="plan-heading">
                                <div className="shadow sm:rounded-md sm:overflow-hidden">
                                    <div className="bg-white py-6 px-4 space-y-6 sm:p-6">
                                        <div>
                                            <h2 id="plan-heading"
                                                className="text-lg leading-6 font-medium text-gray-900">
                                                Plano atual
                                                {!entitlement &&
                                                    <span className="ml-5 inline-flex items-center px-2.5 py-0.5 rounded-md text-sm font-medium bg-yellow-100 text-yellow-800">Teste grátis</span>
                                                }
                                            </h2>
                                        </div>
                                        <dl className="sm:divide-y sm:divide-gray-200">
                                            <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                                <dt className="text-sm font-medium text-gray-500">Armazenamento total</dt>
                                                <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{entitlement ? `${entitlement.max_storage_mb / 1000} GB`: '50 MB'}</dd>
                                            </div>
                                            <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                                <dt className="text-sm font-medium text-gray-500">Máximo usuários</dt>
                                                <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{entitlement ? entitlement.max_users: 1} usuário(s)</dd>
                                            </div>

                                            <div className="rounded-md bg-blue-50 p-4">
                                                <div className="flex">
                                                    <div className="flex-shrink-0">
                                                        <InformationCircleIcon className="h-5 w-5 text-blue-400" aria-hidden="true" />
                                                    </div>
                                                    <div className="ml-3 flex-1 md:flex md:justify-between">
                                                        <p className="text-sm text-blue-700">Caso queira atualizar ou cancelar seu plano, entre em contato com o suporte.</p>
                                                        <p className="mt-3 text-sm md:mt-0 md:ml-6">
                                                            <a onClick={() => $crisp?.push(["do", "chat:open"])} href="#" className="whitespace-nowrap font-medium text-blue-700 hover:text-blue-600">
                                                                Entrar em contato <span aria-hidden="true">&rarr;</span>
                                                            </a>
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </dl>
                                    </div>
                                </div>
                            </section>
                        </div>
                    </div>
                </main>
            </div>
        </>
    )
}