import Head from 'next/head'
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Features from "../components/Features";
import Banner from "../components/Banner";
import FeaturesTwo from "../components/FeaturesTwo";
import Pricing from "../components/Pricing";
import DownloadApp from "../components/DownloadApp";
import FAQ from "../components/FAQ";
import Footer from "../components/Footer";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Skopdoc: Organize imagens dos seus pacientes</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.png"/>
            </Head>

            <nav>
                <Navbar/>
            </nav>

            <main>
                <Banner/>
                <Hero/>
                <Features/>
                <FeaturesTwo/>
                <Pricing/>
                <DownloadApp/>
                <FAQ/>
            </main>

            <Footer/>
        </div>
    )
}
